#!/bin/bash

# Hedgehog Cloud by www.eigener-server.ch https://www.eigener-server.ch/en/igel-cloud \
# is licensed under a Creative Commons Attribution 4.0 International Lizenz \
# http://creativecommons.org/licenses/by/4.0/ \
# To remove the links visit https://www.eigener-server.ch/en/igel-cloud"

MONAT=`date +"%Y-%m"`
DATUM=`date +"%Y-%m-%d"`


BACKUP=/host/mariadb/backup/$MONAT/

mkdir -p $BACKUP
cd $BACKUP

/usr/bin/mysqldump -u MARIADB_USER -pMARIADB_PASS --all-databases | /bin/gzip -9 > all-databases-$DATUM.sql.gz

